Adjust stamina
akasolace/HO pull request #1491
Opened 2022-05-06 19:44 UTC by sophiastr

1. changes proposed in this pull request:
 
   - fixes issue #383  
   
   - if not fixing an existing issue, comments explaining the purpose of the PR should be provided)
 
 
2. changelog and release_notes ...

 - [ ] have been updated
 - [ ] do not require update

3. [Optional] suggested person to review this PR @___

4. About the issue:

If a player has played a game during the week, stamina is adjusted according to the type.
previous stamina - ((3/m_lastMatchRating))^0.2 .
The type does not allow major changes in case of a bad game rating.
Also, I am writing a test to check my code.

2022-05-06 20:58 UTC, sophiastr commented
Hello @wsbrenk, 
I made a pull request. I'm waiting for your feedback.

2022-05-07 06:46 UTC, akasolace commented
Hello @sophiastr,
What I had in mind was not quite that but the following:
 
when a player plays a game you have from match report:
  - time spent on the field 
  - average rating
  - rating at end of game

From the difference between the 2 ratings it is possible to guess the stamina sub levels. Hence we could update them for players after each game...

The issue description might not have been clear. 

What do you think ? Also looking forward to have @wsbrenk inputs ...

2022-05-07 10:04 UTC, sophiastr commented
So, you mean that  the new stamina will be the difference: stamina - (average rating - rating at end of game) ???
Moreover, so far I was working on the Player class, now in which class should I work in order to automatically renew stamina after each game?
Sorry, it was not what you wanted.
I will have the new code soon.

2022-05-08 12:02 UTC, wsbrenk requested changes
We are very grateful for the support. but I'm afraid we still have some things to adjust.

2022-05-10 13:30 UTC, sophiastr commented
Can you give me some more information? For example, in which class are the variables you want to use? In this class?
![image](https://user-images.githubusercontent.com/72817947/167639675-0f27e3e9-ce8d-4d45-bc4e-35abd17546bb.png)

Also, is this the equation?
stamina - (average rating - rating at end of game)

Thank you, @akasolace @wsbrenk

2022-05-11 18:36 UTC, wsbrenk commented
@sophiastr i think Player.calcSubskills is a good place to handle the stamina subskill too.
i would introduce a new variable Player.subStamina to store the guessed stamina subskill.

2022-05-13 10:38 UTC, sophiastr commented
Hello @wsbrenk,

I made some changes.
I am waiting for your feedback.
I, also, fixed the format in Player class.
If the code is what you wanted, tell me to start the tests.

Thank you

2022-05-16 21:46 UTC, sophiastr commented
Good evening again, whenever you have time give me some feedback. I really want to be able to contribute to this project. Tell me if the implementation is ok or if I need to change something.

2022-05-17 12:17 UTC, wsbrenk commented
@sophiastr please excuse me for not coming to the review at the moment - have to harvest honey at the moment and therefore come to nothing else.

2022-05-18 16:46 UTC, wsbrenk requested changes

2022-05-18 16:46 UTC, wsbrenk commented on src/main/java/core/model/player/Player.java
> +            case STAMINA -> getStamina();
in Player.calcsubskill you mention that stamina is the subskill of stamina/kondition (german word for stamina). but here you return it as major value of stamina. major value of stamina is downloaded from hattrick and does not need to be calculated.

2022-05-18 16:46 UTC, wsbrenk commented on src/main/java/core/model/player/Player.java
> +        }
i do not understand this calculation - please explain. i thought the result of substamina should be a double value in the range from 0,00 up to 0.99.

2022-05-18 17:50 UTC, sophiastr commented
Thank you for your feedback @wsbrenk. 
You are completely right. 
I hadn't understood so well the difference between stamina and substamina.
One last question.

Why substamina should be between 0 and 0.99? Since substamina comes from the difference between the 2 ratings (LastMatchRating average rating), it may be greater than 1. Is this true?

2022-05-18 19:25 UTC, sophiastr commented
I made some changes. When you have time, look at them and give me some feedback.
I'm not sure I understand exactly how you want stamina subskill to be calculated but I made an attempt.
If this is not what you want, give me some information and I will change it immediately.
Thank you @wsbrenk ,
Sophia

2022-05-20 16:09 UTC, sophiastr commented
Hello again @wsbrenk ,
Because I have the time and desire to write code, is there any work to be done?
For example, I can deal with the format or Javadoc comments. If there is no job, can I continue with a new issue?
Thank you,
Sophia

2022-05-20 18:33 UTC, masterpatje commented
@sophiastr if you want you can look at issue 1489 how and verify how subskills are calculated. Maybe you can find out if my problem is related to substitutes not being calculated correctly. You might look at the code and see how the calculation of subskills is done.

2022-05-22 11:41 UTC, sophiastr commented
Of course, I will deal with the issue that you suggested to me @masterpatje .
I need a couple of days to do a test for the code I delivered.
It is very important for me to be able to merge within a week. So as soon as you find time, give me some feedback. Thank you and sorry @wsbrenk .

2022-05-24 13:00 UTC, sophiastr commented
Hello @wsbrenk ,

I am really sorry to bother you, but please check my pull request when you find the time.

Thank you and sorry.
Sophia

2022-05-24 13:15 UTC, sophiastr reviewed
Calculate Stamina Subskill

2022-05-24 13:26 UTC, wsbrenk requested changes

2022-05-24 13:44 UTC, sophiastr commented on src/main/java/core/model/player/Player.java
> +            setSubStamina(subStamina);
Thank you for your feedback. While I was trying to solve the issue, I used many variables, above them the last game rating, and the average rating of the last game. But all the getters in PlayerInfo return null. Have you noticed this problem? That's why I used getBewertungen4Player. Do you want to understand first why it returns null and then use those variables in the formula?

2022-06-05 00:25 UTC, sophiastr commented
Good evening @wsbrenk , do you know if LastMatch_RatingEndOfGame information is stored somewhere? Is this information somewhere? Because in all the ways I tried to get it, I did not succeed.
I tried in so many ways.
They return null or 0.
Can you tell me if you have this problem too?
If you do not have the same problem can you send me the command to have access?

Sophia

2022-06-05 10:13 UTC, wsbrenk commented
@sophiastr 

in constructor of class PlayerInfo i find this:
~~~
        this.rating = Float.parseFloat(i.get("LastMatch_Rating"));
        this.lastMatchId = Integer.parseInt(i.get("LastMatch_id"));
        this.lastMatchPosition = Integer.parseInt(i.get("LastMatch_PositionCode"));
        this.lastMatchPlayedMinutes = Integer.parseInt(i.get("LastMatch_PlayedMinutes"));
        this.lastMatchRatingEndOfGame = Float.parseFloat(i.get("LastMatch_RatingEndOfGame"));
~~~

i willl now try to find out if we could use it and where it comes from

2022-06-05 10:28 UTC, wsbrenk commented
i do not find any playe where this information is stored in the database. it looks like it is only temporary available and not used in any place for now.
class PlayerInfo is used in the team analyzer module. there is a lot to do, to get this running (database update and so on). 

i have moved this to the milestone 7. tell me if you want to analyze the things that needs to be done or if you want me to do it?
i think we have to find a solution how to get this info in the database table SPIELER (player).

2022-06-06 13:58 UTC, sophiastr commented
Hello @wsbrenk ,
Thank you very much for your help. Now that I have the information, I will try to fix the method again. I am thinking of doing this:
ratingEndOfGame - averageRatingOfLastGame
In this way, if the number is positive it means high stamina otherwise if it is negative the number means low stamina.
Is this approach correct and what do you want me to do?

Sophia

2022-06-06 14:01 UTC, sophiastr commented
Hello @wsbrenk ,
Thank you very much for your help. Now that I have the information, I will try to fix the method again. I am thinking of doing this:
ratingEndOfGame - averageRatingOfLastGame
In this way, if the number is positive it means high stamina otherwise if it is negative the number means low stamina.
If the difference is big and positive then it means very high stamina.
This is how I would approach it.
Is this approach correct and what do you want me to do?

Sophia

2022-06-06 20:49 UTC, sophiastr commented
Thanks a lot for the help @wsbrenk . Can I continue in Player class ? I will send you how I intend to do my method in a little while.

2022-06-06 22:58 UTC, sophiastr commented
Hello again @wsbrenk 
I still do not have access to the information needed.
I used the method you created in Player class but it returns null.
I also used this command: DBManager.instance().getTALatestPlayerInfo(getPlayerID()).getLastMatchRatingEndOfGame()
All the methods in PlayerInfo return Null or 0.
Moreover, I need another variable to calculate stamina subskill. I need averageRatingOfLastMatch.
This variable exists in PlayerInfo and Player class but the getters in each class return zero.

Finally, I thought of a new idea to calculate stamina subskill.
Here is my proposal:

If LastMatch_RatingEndOfGame > averageRatingOfLastMatch means an increase in stamina.
As a result i calculate stamina subskill based on this formula: (LastMatch_RatingEndOfGame -averageRatingOfLastMatch) / 10
great difference means high stamina
10-2= 6/10(great increase)
If LastMatch_RatingEndOfGame < averageRatingOfLastMatch means a decrease in stamina.
As a result, i calculate stamina subskill based on this formula: (averageRatingOfLastMatch - LastMatch_RatingEndOfGame) / 10
great difference means low stamina
 6-2=4/10(big decrease)
Finally, if there is an increase, I add the stamina subskill
If there is a decrease, I deduct the stamina subskill

It makes sense, though if you want something more complicated then tell me to try.
Tell me your opinion.
If you want me to proceed with your idea, please give me information or a formula because I do not understand how a simple subtraction can cover all the scenarios. 


Sophia

2022-06-08 14:18 UTC, sophiastr commented
Hello @wsbrenk ,

When you have time, see why the method you made returns Null so I can move on.
Thank you and sorry
Sophia

2022-06-11 08:26 UTC, wsbrenk commented
@sophiastr the values of LastMatch_RatingEndOfGame are only available in new downloaded matches. HO will not download "old" matches automatically. please check if the new methods returns null even in new downloaded matches - this should not happen!

concerning your ideas: 
* RatingEndOfGame is never greater than AverageRating => your formulas will only give "decrease" of stamina.

2022-06-11 11:01 UTC, wsbrenk commented
@sophiastr before further investigating on that stamina formula (i don't have any idea, how it should work) you could start making the three new lastmatch values available in the squad table view. this should be a little bit easier.

2022-06-12 06:26 UTC, masterpatje commented
> @sophiastr the values of LastMatch_RatingEndOfGame are only available in new downloaded matches. HO will not download "old" matches automatically. please check if the new methods returns null even in new downloaded matches - this should not happen!
> 
> 
> 
> concerning your ideas: 
> 
> * RatingEndOfGame is never greater than AverageRating => your formulas will only give "decrease" of stamina.
> 
> 

Actually it is possible in very rare occassions that the RatingEndOfGame is higher than average rating. I don't know if this still happens and what conditions triggers it. Maybe changed weather condition during the match in combination with a specialty that was penalised by certain weather conditions that are no longer present? If I remember correctly hattrick shows this by a different colour in the stars... might be red that indicated the gain in ratings and the red stars represent the increase.

Suggestion: add line of code that in these rare events the rating end of game is adjusted to / equal to the average rating.

Best of luck.

2022-06-26 15:33 UTC, closed without merging